version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #   - ./ .env
    environment:
#      - DATABASE_HOSTNAME=postgres
#      - DATABASE_PORT=5432
#      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
#      - DATABASE_USERNAME=postgres
      - SECRET_KEY=9e29b918d26bf37fbd7a9c9aee61e4f7eff9edb3f1d70e4d59323203c91bbb18
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#    depends_on:
#      - postgres

#  postgres:
#    image: postgres:16-alpine
#    environment:
#      - POSTGRES_PASSWORD=password123
#      - POSTGRES_DB=fastapi
#    volumes:
#      - postgres-db:/var/lib/postgresql/data
#
#volumes:
#  postgres-db:
