name: Build And Deploy Code

on: [push, pull_request]

jobs:
  Build:
    environment:
      name: Testing
    env:
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git Repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: |
          pip install pytest
          pytest
  Deploy:
    environment:
      name: Production
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Pull Git Repo
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deployed with success"
